[variables]
NODE_ENV = "production"
JWT_SECRET = "drevmaster-secret-key-2024"

[phases.build]
cmds = [
  "npm ci --only=production",
  "npm run build"
]

[phases.setup]
cmds = [
  "mkdir -p /app/data",
  "chmod 755 /app/data"
]

[start]
cmd = "bash start.sh" 